### ISSUE TITLE
vagrnat up asking password

### ISSUE THREAD

**Issue by bastianvs** [lloydmeta/ansible-kafka-cluster#2]
==> zk-node-1: Updating /etc/hosts file on active guest machines...
==> zk-node-1: Updating /etc/hosts file on host machine (password may be required)...
Password: 

what is the password?

**Comment by lloydmeta** [comment]
This would be your sudo password, since /etc/hosts often requires admin rights to modify. This prompt is implemented via the [`vagrant-hostmanager`](https://github.com/smdahlen/vagrant-hostmanager) vagrant plugin

**Comment by lloydmeta** [comment]
If you're still having problems after providing your sudo password, please let me know.

**Comment by bastianvs** [comment]
It went through but i am not seeing any anisible roles loaded i just got 6 new vagrant nodes

**Comment by bastianvs** [comment]
==> kafka-node-3: Running provisioner: ansible...
    kafka-node-3: Running ansible-playbook...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --connection=ssh --timeout=30 --limit='all' --inventory-file=/Users/vbastian/Misc/ansible-kafka-cluster/.vagrant/provisioners/ansible/inventory --extra-vars={"accept_oracle_licence":true,"vagrant_zk_client_port":2181,"vagrant_zk_cluster_info":{"zk-node-1":{"zk_id":1},"zk-node-2":{"zk_id":2},"zk-node-3":{"zk_id":3}},"vagrant_kafka_cluster_info":{"kafka-node-1":{"broker_id":1},"kafka-node-2":{"broker_id":2},"kafka-node-3":{"broker_id":3}}} --sudo -vv site.yml
ERROR: /Users/vbastian/Misc/ansible-kafka-cluster/roles/zookeeper/defaults/main.yml: Expecting value: line 1 column 2 (char 1)
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by lloydmeta** [comment]
Strange, looks like a syntax error on [the zookeeper defaults file](https://github.com/lloydmeta/ansible-kafka-cluster/blob/master/roles/zookeeper/defaults/main.yml), but throwing it into a YAML lint shows no errors and it doesn't fail with that error for me. 

Is there any chance you have modified that file?

**Comment by bastianvs** [comment]
Yes it was modified its working now you can close this issue
